### ISSUE TITLE
插件启动过程ui-tabs-callback抛出异常

### ISSUE THREAD

**Issue by redcats2** [miaoshouai/miaoshouai-assistant#1]
_webui为Automatic1111 latest_

SD-WebUI Launcher Diagnostic File

Date: 2023-04-27 08:28:19
Launcher Version: 2.0.11.0
Data File Version: 2023-04-25 22:30
SD-WebUI Version: 22bcc7be428c94e9408f589966c2040187245d81 (2023-03-29 13:58:29)
Working Directory: D:\StableDiffusion\stable-diffusion-webui
------------------------
System Information: 
OS: Microsoft Windows NT 10.0.19044.0
CPU: 12 cores
Memory Size: 16384 MB
Page File Size: 1786 MB
CUDA Version: 12010
Available CUDA Engines: 
    00000000:01:00.0: NVIDIA P106-100 6 GB
=====================

------------------------
Log: 
Python 3.10.9 (tags/v3.10.9:1dd9be6, Dec  6 2022, 20:01:21) [MSC v.1934 64 bit (AMD64)]
Commit hash: 22bcc7be428c94e9408f589966c2040187245d81
Installing requirements for Web UI

Launching Web UI with arguments: --medvram --theme dark --xformers --no-half-vae --autolaunch --api --no-hashing
logs_location: D:\StableDiffusion\stable-diffusion-webui\extensions\miaoshouai-assistant\logs
[AddNet] Updating model hashes...

[AddNet] Updating model hashes...

ControlNet v1.1.112
ControlNet v1.1.112
Loading weights [64b14b6ca5] from D:\StableDiffusion\stable-diffusion-webui\models\Stable-diffusion\02_NeverEnding Dream 1.9(NED)_bakedVae.safetensors
Creating model from config: D:\StableDiffusion\stable-diffusion-webui\configs\v1-inference.yaml
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.52 M params.
Loading VAE weights specified in settings: D:\StableDiffusion\stable-diffusion-webui\models\VAE\vae-ft-mse-840000-ema-pruned.safetensors
Applying xformers cross attention optimization.
Textual inversion embeddings loaded(0): 
Model loaded in 2.1s (load weights from disk: 0.1s, create model: 0.5s, apply weights to model: 0.6s, apply half(): 0.7s, load VAE: 0.1s).
Error executing callback ui_tabs_callback for D:\StableDiffusion\stable-diffusion-webui\extensions\miaoshouai-assistant\scripts\main.py
Traceback (most recent call last):
  File "D:\StableDiffusion\stable-diffusion-webui\modules\script_callbacks.py", line 125, in ui_tabs_callback
    res += c.callback() or []
  File "D:\StableDiffusion\stable-diffusion-webui\extensions\miaoshouai-assistant\scripts\assistant\miaoshou.py", line 31, in on_event_ui_tabs_opened
    self.create_subtab_boot_assistant()
  File "D:\StableDiffusion\stable-diffusion-webui\extensions\miaoshouai-assistant\scripts\assistant\miaoshou.py", line 42, in create_subtab_boot_assistant
    gpu, theme, port, chk_args, txt_args, webui_ver = self.runtime.get_default_args()
  File "D:\StableDiffusion\stable-diffusion-webui\extensions\miaoshouai-assistant\scripts\runtime\msai_runtime.py", line 65, in get_default_args
    theme = [k for k, v in self.prelude.theme_setting.items() if v == arg][0]
IndexError: list index out of range

Running on local URL:  http://127.0.0.1:7860

To create a public link, set `share=True` in `launch()`.
Startup time: 9.2s (import torch: 1.7s, import gradio: 1.0s, import ldm: 0.5s, other imports: 0.8s, load scripts: 1.6s, load SD checkpoint: 2.2s, create ui: 1.0s, gradio launch: 0.3s).

**Comment by miaoshouai** [comment]
fixed. pull to update. 
was caused by the different use of theme parameter from the booter app.
