### ISSUE TITLE
Cannot specify a different folder for my models, error - returned non-zero exit status 1.

### ISSUE THREAD

**Issue by RealTekHousE** [miaoshouai/miaoshouai-assistant#10]
I have tried to change my default models folder to one on another drive. 

I have changed the default folder name to __OLDmodels

I then specify my new folder path, but I get this error - returned non-zero exit status 1.

There is another problem, on launch of SD, the launcher recreates that Model folder anyway. And then downloads a checkpoint. I'd love to move my model folder as it is massive, to the newer hard drive. What am I doing wrong?

**Comment by RealTekHousE** [comment]
OK..I tried a few things and ended up deleting the model folder before trying to link. I misunderstood what yoru script was doing. I see now that it needed NO Model folder than it creates a link. 

Sorry but that wasn't immediately clear to me in the instructions.

**Comment by miaoshouai** [comment]
yeah~ the model folder need to be removed to somewhere else before link
