### ISSUE TITLE
Issue with "Model Management" tab if models are in subfolders

### ISSUE THREAD

**Issue by MeeJay** [miaoshouai/miaoshouai-assistant#14]
The "Model Management" tab is hanging on "processing" forever if you select a model that's inside a subfolder.

Step to reproduce:
1) Put a model inside a subfolder (e.g : Stable-Diffusion\test\sd-v1-4.ckpt)
2) Refresh models list or restart SD.
3) Go to Miaoshou => Model Management, and validate Miaoshou Assistant work by selecting any model that are not in subfolder.
- You should be able to see the Model Cover and get the prompts as intended
- You can change model, switch from Checkpoint to Lora, etc...
4) Select the model that's inside the subfolder
- Miaoshou Assistant will hang on "Processing" forever
5) Try to rollback to a "working" model
- Miaoshou Assistant will stay stuck, it will not switch to the model you've just selected.

Managing model with subfolders is a really usefull feature of the WebUI when you have a big library, but being able to get model's prompts with Miaoshou Assistant is also a killer feature, so I hope someone could get a fix for that :)

**Comment by miaoshouai** [comment]
be able to repreduce the sub folder error. looking into it and adding it to the next release update

**Comment by MeeJay** [comment]
> be able to repreduce the sub folder error. looking into it and adding it to the next release update

Thanks! That's really nice to read :)

**Comment by miaoshouai** [comment]
ok, give it a try. it's in there now in 1.4. try the update button first, you may need to shutdown webui for this latest update, or maybe a reinstall of the extension. haven't done enough testing on the update part. if you see a chatgpt prompt box in model management, that means you got it right.

**Comment by MeeJay** [comment]
I can see the "ChatGPT" Prompt Box and i'm able to get info for models in subfolder. Nice work !
