### ISSUE TITLE
扩展钩子执行失败尝试执行扩展 miaoshouai-assistant 的 ui tabs callback 钩子时出现异常，这可能表示扩展版本与本体版本不兼容

### ISSUE THREAD

**Issue by mikumikuEgg** [miaoshouai/miaoshouai-assistant#2]
<img width="960" alt="微信截图_20230428110002" src="https://user-images.githubusercontent.com/27794352/235090205-c83258d2-08c8-4460-ba82-e4f1ae413b35.png">

已经尝试更新到最新版本仍没有解决

**Comment by miaoshouai** [comment]
models\stabel-diffusion下面有camelliamix25d_v1这个模型但是没有camelliamix25d_v1.png这样封面？

**Comment by miaoshouai** [comment]
刚刚推了一个新版本 你看看还会有这个问题不
