### ISSUE TITLE
Missing tab with recent Stable Diffuse update

### ISSUE THREAD

**Issue by Wolf1030** [miaoshouai/miaoshouai-assistant#22]
Windows 10. I've uninstalled and reinstalled the extention.
![brave_lNd2tabmGp](https://github.com/miaoshouai/miaoshouai-assistant/assets/8041394/56ca2acd-27a8-4938-913e-71936087c53e)

**Comment by miaoshouai** [comment]
could you show me if there is any error msg from the console?

**Comment by Wolf1030** [comment]
![cmd_NjX6JMujoQ](https://github.com/miaoshouai/miaoshouai-assistant/assets/8041394/e961bfb3-0af0-439b-b746-aaccce90994c)

Please disregard, sorta. It's for some reason functional now. After a few restarts of Stable Diffuse it finally popped up again, no idea why it disappeared before, but it is working again.
