### ISSUE TITLE
downloading files ist failing. 

### ISSUE THREAD

**Issue by benjamin-bertram** [miaoshouai/miaoshouai-assistant#45]
Hey there, first of all I love the functionality, and ease of your extension. Unfortunately the download does not work. I get stuck with this everytime I want to download something. 

<img width="826" alt="Screenshot 2023-09-14 at 15 02 13" src="https://github.com/miaoshouai/miaoshouai-assistant/assets/54454305/389c63bd-f067-4ea2-b70b-eb9c3b9f4ef5">

There is no indicator why it failed in the terminal however the log gives me this: 

` 2023-09-13 23:53:34,265 - msai_file_downloader.py [line:108] - ERROR: failed to load downloading checkpoint - /Users/benjaminbertram/.miaoshou_assistant_download/EasyNegative.jpg.downloading due to [Errno 2] No such file or directory: '/Users/benjaminbertram/.miaoshou_assistant_download/EasyNegative.jpg.downloading'
`

I looked up the line, but i cannot see why it is failing, also i could not find the download function itself, to see if there is a problem with it. When I am using the batchlinks downloader extension for example the download is going just fine, I am using wget/ gdown there. 

I searched the issues and the web but did not find a solution yet. I am on Mac M1 Ventura 13.3.1, tested the webui on different browsers, the bug remains the same.

**Comment by miaoshouai** [comment]
it might be a permission error that the downloader does not have folder permission to create the temp download folder. just a wild guess based on the limited information given. try to create the .miaoshou_assistant_download yourself and see if the error is still there

**Comment by benjamin-bertram** [comment]
There seems to be something towards it. When I wanted to created the directory I got an error, stating the .* directories are just for the system.

However, when I changed the line 70 in msai_toolkit.py

```
def get_user_temp_dir() -> str:
    return os.path.join(Path.home().absolute(), ".miaoshou_assistant_download")
```

to `"miaoshou_assistant_download"` (without the dot) and created the resembling directory I got the same error.

**Comment by triphop** [comment]
when the miaoshou downloader cannot find out the downloading checkpoint file, It will reset its internal state, that means, it will download the model file from the beginning and everything should go well in this case.

I think the issue may be not related the file/folder permission.

please use another branch [bugfix/gradio_api_incompatibility](https://github.com/miaoshouai/miaoshouai-assistant/tree/bugfix/gradio_api_incompatibility) to see whether the issue above is gone.

```sh
cd <your_stable_diffusion_directory>/extensions/miaoshouai-assistant/
git checkout -b verfication origin/bugfix/gradio_api_incompatibility
git pull --rebase -p
```

change the 'disable_log_console_output" from **true** to **false** to switch on log output to console, so we can get detailed info.

```text
vim <your_stable_diffusion_directory>/extensions/miaoshouai-assistant/configs/settings.json

{
   ....
   "disable_log_console_output": false,
   ....
}
```

and after then, please **restart your webui again**

**Comment by benjamin-bertram** [comment]
That did it! Thanks a lot, I finally can download now :)
