### ISSUE TITLE
Assets.Git Download From A Site Other Than GitHub?

### ISSUE THREAD

**Issue by cashea** [miaoshouai/miaoshouai-assistant#46]
There appear to be assets which are not sourcing from GitHub during a clone.  These assets drag the download speed almost to a standstill.  Is there a reason the assets.git file is not stored on GitHub?

The files are requested from:  https://e.coding.net/miaoshouai/miaoshou-stable-diffusion-webui/assets.git

                           stderr: 'Cloning into '...\automatic\tmp\miaoshouai-assistant\assets'...
                         POST git-upload-pack (185 bytes)
                         POST git-upload-pack (277 bytes)
                         error: RPC failed; curl 56 OpenSSL SSL_read: OpenSSL/3.1.2: error:1C800066:Provider routines::cipher operation failed, errno 0
                         error: 4021 bytes of body are still expected
                         fetch-pack: unexpected disconnect while reading sideband packet
                         fatal: early EOF
                         fatal: fetch-pack: invalid index-pack output
                         '

**Comment by mikheys** [comment]
Affirmative. I have the same problem.

**Comment by miaoshouai** [comment]
> There appear to be assets which are not sourcing from GitHub during a clone. These assets drag the download speed almost to a standstill. Is there a reason the assets.git file is not stored on GitHub?
> 
> The files are requested from: https://e.coding.net/miaoshouai/miaoshou-stable-diffusion-webui/assets.git
> 
> ```
>                        stderr: 'Cloning into '...\automatic\tmp\miaoshouai-assistant\assets'...
>                      POST git-upload-pack (185 bytes)
>                      POST git-upload-pack (277 bytes)
>                      error: RPC failed; curl 56 OpenSSL SSL_read: OpenSSL/3.1.2: error:1C800066:Provider routines::cipher operation failed, errno 0
>                      error: 4021 bytes of body are still expected
>                      fetch-pack: unexpected disconnect while reading sideband packet
>                      fatal: early EOF
>                      fatal: fetch-pack: invalid index-pack output
>                      '
> ```

Just uploaded a release. the reason for the assets file being hosted outside github is because github's limitation for large file hosting. If you need the asset file for v1.7, just go to release or find tag v1.7 and download it from there. all you need is the three files under assets folder and place them there.
