### ISSUE TITLE
Feature request: Sorting Models

### ISSUE THREAD

**Issue by reetkont** [miaoshouai/miaoshouai-assistant#52]
Right now, the search results on the Download Models tab are sorted by "rating". Can you please add a dropdown to allow sorting the results based on other stats like "downloadCount", "favoriteCount", commentCount" and "ratingCount"? Possibly to the management tab as well.

Edit: an additional dropdown for period (all time, year, month, etc) would be nice as well. Though not sure if this can be done with the current available model datacollection.

**Comment by miaoshouai** [comment]
feature included in the latest v1.8 version. update miaoshouai to obtain the sorting feature
